//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanProject.Resources.Text_Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HangmanProject.Resources.Text_Files.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extinct
        ///kinship
        ///liberty
        ///confuse
        ///trouser
        ///council
        ///veteran
        ///volcano
        ///lecture
        ///percent
        ///average
        ///collect
        ///mystery
        ///realism
        ///perfect
        ///reserve
        ///laborer
        ///certain
        ///obscure
        ///illness.
        /// </summary>
        internal static string txtEasy {
            get {
                return ResourceManager.GetString("txtEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blackmail
        ///craftsman
        ///machinery
        ///formulate
        ///computing
        ///offensive
        ///precision
        ///penetrate
        ///chocolate
        ///intention
        ///foreigner
        ///notorious
        ///biography
        ///plaintiff
        ///wisecrack
        ///consensus
        ///automatic
        ///courtship
        ///exception
        ///freighter.
        /// </summary>
        internal static string txtHard {
            get {
                return ResourceManager.GetString("txtHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to definite
        ///election
        ///ideology
        ///argument
        ///contrary
        ///threaten
        ///electron
        ///assembly
        ///sunshine
        ///reliable
        ///quantity
        ///category
        ///interest
        ///faithful
        ///bathroom
        ///obstacle
        ///complete
        ///resident
        ///courtesy
        ///indirect.
        /// </summary>
        internal static string txtMedium {
            get {
                return ResourceManager.GetString("txtMedium", resourceCulture);
            }
        }
    }
}
